"""add store config

Revision ID: 268848d3039f
Revises: ce05b71fbbbb
Create Date: 2026-04-11 16:08:04.415972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268848d3039f'
down_revision: Union[str, None] = 'ce05b71fbbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gam_shipping_cost', sa.Float(), nullable=True),
    sa.Column('non_gam_shipping_cost', sa.Float(), nullable=True),
    sa.Column('gam_delivery_days', sa.String(), nullable=True),
    sa.Column('non_gam_delivery_days', sa.String(), nullable=True),
    sa.Column('sinpe_number', sa.String(), nullable=True),
    sa.Column('sinpe_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_config_id'), 'store_config', ['id'], unique=False)
    op.add_column('gifts', sa.Column('shipping_cost_applied', sa.Float(), nullable=True))
    op.add_column('gifts', sa.Column('payment_receipt_url', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('payment_receipt_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'payment_receipt_method')
    op.drop_column('gifts', 'payment_receipt_url')
    op.drop_column('gifts', 'shipping_cost_applied')
    op.drop_index(op.f('ix_store_config_id'), table_name='store_config')
    op.drop_table('store_config')
    # ### end Alembic commands ###
