"""add_farm_table

Revision ID: 5c436d043539
Revises: a94f4210968c
Create Date: 2026-04-03 19:21:10.316954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c436d043539'
down_revision: Union[str, None] = 'a94f4210968c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_trees', sa.Integer(), nullable=True),
    sa.Column('trees_sold', sa.Integer(), nullable=True),
    sa.Column('carbon_capacity_tons', sa.Float(), nullable=True),
    sa.Column('gps_location', sa.String(), nullable=True),
    sa.Column('caretaker_name', sa.String(), nullable=True),
    sa.Column('caretaker_contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_index(op.f('ix_farms_name'), 'farms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farms_name'), table_name='farms')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
