"""usd to crc

Revision ID: 628d5e659a8b
Revises: 82cb42869625
Create Date: 2026-04-11 23:02:59.922118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628d5e659a8b'
down_revision: Union[str, None] = '82cb42869625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree_species', sa.Column('price_crc', sa.Integer(), server_default='12875', nullable=False))
    op.drop_column('tree_species', 'price_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree_species', sa.Column('price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tree_species', 'price_crc')
    # ### end Alembic commands ###
