"""Add whatsapp, address, invoices

Revision ID: 7a716ff5fb57
Revises: 875a2ea0b5f0
Create Date: 2026-04-03 21:41:12.148128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a716ff5fb57'
down_revision: Union[str, None] = '875a2ea0b5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_invoices_id'), 'subscription_invoices', ['id'], unique=False)
    op.add_column('users', sa.Column('whatsapp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'whatsapp')
    op.drop_index(op.f('ix_subscription_invoices_id'), table_name='subscription_invoices')
    op.drop_table('subscription_invoices')
    # ### end Alembic commands ###
