"""invoice additional fields

Revision ID: 82cb42869625
Revises: f50ac750d573
Create Date: 2026-04-11 16:49:37.238366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cb42869625'
down_revision: Union[str, None] = 'f50ac750d573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('invoice_name', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('invoice_id_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'invoice_id_number')
    op.drop_column('gifts', 'invoice_name')
    # ### end Alembic commands ###
