"""add_amount_usd_to_subscriptions

Revision ID: 875a2ea0b5f0
Revises: e660fbcebd7a
Create Date: 2026-04-03 21:18:52.896251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875a2ea0b5f0'
down_revision: Union[str, None] = 'e660fbcebd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('amount_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'amount_usd')
    # ### end Alembic commands ###
