"""gam cantons

Revision ID: b9278de73473
Revises: 268848d3039f
Create Date: 2026-04-11 16:14:27.431307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9278de73473'
down_revision: Union[str, None] = '268848d3039f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_config', sa.Column('gam_cantons', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_config', 'gam_cantons')
    # ### end Alembic commands ###
