"""add_tree_stock_and_active

Revision ID: ce05b71fbbbb
Revises: f920caa12345
Create Date: 2026-04-11 03:48:17.036807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce05b71fbbbb'
down_revision: Union[str, None] = 'f920caa12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree_species', sa.Column('stock', sa.Integer(), server_default='100', nullable=False))
    op.add_column('tree_species', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree_species', 'is_active')
    op.drop_column('tree_species', 'stock')
    # ### end Alembic commands ###
