"""buyer fields

Revision ID: f50ac750d573
Revises: b9278de73473
Create Date: 2026-04-11 16:32:31.029273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50ac750d573'
down_revision: Union[str, None] = 'b9278de73473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('buyer_last_name', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('buyer_whatsapp', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('invoice_requested', sa.Boolean(), nullable=True))
    op.add_column('gifts', sa.Column('invoice_address', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('invoice_activity_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'invoice_activity_code')
    op.drop_column('gifts', 'invoice_address')
    op.drop_column('gifts', 'invoice_requested')
    op.drop_column('gifts', 'buyer_whatsapp')
    op.drop_column('gifts', 'buyer_last_name')
    # ### end Alembic commands ###
